version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.0.1.0/28
  

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - fides.develop

  eventBus:
    image: rabbitmq:3.8-alpine
    networks:
      default:
        ipv4_address: 192.0.1.1
    volumes:
      - ../volumes/rabbit:/etc/rabbit
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - 15672:15672

  cache:
    image: redis:6-alpine
    networks:
      default:
        ipv4_address: 192.0.1.2
    command: redis-server --requirepass root
    ports:
      - 6379:6379
   
  mongo:
    image: mongodb:4.4
    networks:
      default:
        ipv4_address: 192.0.1.3
    volumes:
      - ../volumes/mongo:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    
  user-service:
    build: Dockerfile-golang-run
    networks:
      default:
        ipv4_address: 192.0.1.4
    environment:
      REDIS_URI: redis://default:root@cache:6379
      MONGO_URI: mongodb://root:root@mongo:27017
      RABBIT_MQ_URI: amqp://root:root@eventBus:15672
      PORT: 4000