version: "3"

networks:
  fides-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.1.0/28
  

services:
  nginx:
    image: nginx:stable-alpine
    hostname: fides.local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    # depends_on:
    #   - user-service
    networks:
      fides-net:
        ipv4_address: 172.0.1.2
        aliases:
          - fides.develop

  eventBus:
    image: rabbitmq:3.8-alpine
    hostname: eventBus
    networks:
      fides-net:
        ipv4_address: 172.0.1.3
    volumes:
      - ../volumes/rabbit:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672

  cache:
    image: redis:6-alpine
    networks:
      fides-net:
        ipv4_address: 172.0.1.4
    command: redis-server --requirepass root
    ports:
      - 6379:6379
   
  mongo:
    image: mongo:4.4
    networks:
      fides-net:
        ipv4_address: 172.0.1.5
    volumes:
      - ../volumes/mongo:/etc/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    
  # user-service:
  #   image: fides.user-service
  #   restart: always
  #   build:
  #     context: ../
  #     dockerfile: deployment/Dockerfile
  #     args:
  #       service: user-service
  #   depends_on:
  #     - cache
  #     - eventBus
  #     - mongo
  #   networks:
  #     fides-net:
  #       ipv4_address: 172.0.1.6
  #   environment:
  #     - REDIS_URI=redis://default:root@cache:6379/
  #     - MONGO_URI=mongodb://root:root@mongo:27017/
  #     - RABBIT_MQ_URI=amqp://root:root@eventBus:5672/
  #     - PORT=4000